# openzone-radio/tools/icons/make_icons.py
"""Draw the PDA glue's icon atlas and write its imageset.

ONE SPRITE, and that is the whole point (owner decision 2026-09-09): a page's
tab icon comes from the module that registers the page. `tab_radio` used to
live in the PDA's own atlas -- the picture of a mod the PDA does not contain --
so the radio could not gain a tab without the PDA gaining the picture. Now the
glue that brings the page brings the picture with it.

The geometry is the PDA's, on purpose: 4x oversampled, downscaled to a 56 px
sprite in a 64 px cell with a 4 px gutter, white on transparent so the widget's
`color` tints it. The drawing below is a copy of the `@sprite("tab_radio")`
block that stood in openzone-pda/tools/icons/make_icons.py, so the picture is
the same picture, not a redrawing of it.

Needs Pillow, installed in the MCP repo's venv:
E:/dayzmod/dayz-agentic-modding-mcp/.venv -- run this with that venv's python,
not a bare `python`.

    <venv python> tools/icons/make_icons.py     # writes the PNG and the .imageset

Then convert the PNG with the MCP tool asset_convert -> oz_radio_icons_ca.paa
(the _ca suffix keeps the alpha; _co would drop it). The set is registered in
OpenZone_Radio_PDA/config.cpp (class imageSets); a layout refers to a sprite as
`image0 "set:oz_radio_icons image:tab_radio"`, and the tab rail is told the
same reference by OZ_PdaPageFactory.Sprite().
"""
from __future__ import annotations

from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[2]
OUT_DIR = ROOT / "OpenZone_Radio_PDA" / "gui" / "imagesets"
SET_NAME = "oz_radio_icons"
TEXTURE = "OpenZone_Radio_PDA/gui/imagesets/oz_radio_icons_ca.paa"
# One cell is the whole sheet here. 64 is a power of two, which the paa
# converter wants, and a 512x512 sheet for a single sprite would ship
# 255 empty cells.
SHEET = 64
CELL = 64
GUTTER = 4
SPRITE = CELL - 2 * GUTTER   # 56
S = 4                        # oversampling factor
W = (255, 255, 255, 255)
CLEAR = (0, 0, 0, 0)

SPRITES: list[tuple[str, object]] = []


def sprite(name: str):
    def register(fn):
        SPRITES.append((name, fn))
        return fn
    return register


def u(v: float) -> float:
    return v * S


def bbox(x0, y0, x1, y1):
    return (u(x0), u(y0), u(x1), u(y1))


def ring(d, cx, cy, r, w=4, start=0, end=360):
    d.arc(bbox(cx - r, cy - r, cx + r, cy + r), start=start, end=end, fill=W, width=int(u(w)))


def disc(d, cx, cy, r, fill=W):
    d.ellipse(bbox(cx - r, cy - r, cx + r, cy + r), fill=fill)


@sprite("tab_radio")
def _(d):
    disc(d, 28, 42, 4)
    for r in (12, 20, 28):
        ring(d, 28, 42, r, w=4, start=210, end=330)


def draw_sprite(fn) -> Image.Image:
    img = Image.new("RGBA", (SPRITE * S, SPRITE * S), CLEAR)
    fn(ImageDraw.Draw(img))
    return img.resize((SPRITE, SPRITE), Image.LANCZOS)


def write_imageset(names: list[str], path: Path) -> None:
    per_row = SHEET // CELL
    lines = ["// GENERATED by tools/icons/make_icons.py -- edit the script, not this file.",
             "ImageSetClass {", f' Name "{SET_NAME}"', f" RefSize {SHEET} {SHEET}", " Textures {",
             "  ImageSetTextureClass {", "   mpix 0", f'   path "{TEXTURE}"', "  }", " }", " Images {"]
    for i, name in enumerate(names):
        px = (i % per_row) * CELL + GUTTER
        py = (i // per_row) * CELL + GUTTER
        lines += [f"  ImageSetDefClass {name} {{", f'   Name "{name}"', f"   Pos {px} {py}",
                  f"   Size {SPRITE} {SPRITE}", "   Flags 0", "  }"]
    lines += [" }", " Groups {", " }", "}"]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def main() -> int:
    if len(SPRITES) > (SHEET // CELL) ** 2:
        raise SystemExit(f"{len(SPRITES)} sprites do not fit {SHEET}x{SHEET}")
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    sheet = Image.new("RGBA", (SHEET, SHEET), CLEAR)
    per_row = SHEET // CELL
    for i, (name, fn) in enumerate(SPRITES):
        px = (i % per_row) * CELL + GUTTER
        py = (i // per_row) * CELL + GUTTER
        sheet.paste(draw_sprite(fn), (px, py))
    png = OUT_DIR / f"{SET_NAME}_ca.png"
    sheet.save(png)
    write_imageset([name for name, _fn in SPRITES], OUT_DIR / f"{SET_NAME}.imageset")
    print(f"wrote {png} ({len(SPRITES)} sprites) and {SET_NAME}.imageset")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
